Add missing QPointer include
Fixes the build with -DBUILD_EXAMPLES=TRUE, which fails with
"httpContainer.h:34:20: error: field 'm_job' has incomplete type
'QPointer<KJob>'" otherwise.